### ISSUE TITLE
0500 ERROR File NOT Found: Player

### ISSUE THREAD

**Issue by Marquis2de3Carabas** [paladini/aax2mp3-easy#19]
Hello,

I think I'm close to it, but aax2mp3_easy ends up with the ERROR mentioned above.
Heres the output:

Traceback (most recent call last):
  File "audible-activator-feature_login_as_arg/audible-activator.py", line 148, in <module>
    fetch_activation_bytes(username, password, options)
  File "audible-activator-feature_login_as_arg/audible-activator.py", line 57, in fetch_activation_bytes
    executable_path=chromedriver_path)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

2019-11-05 14:38:06-0500 ERROR File NOT Found: Player

Any Ideas? Thank you so far.

**Comment by vanson44** [comment]
Hello,

You need to lanch program in a terminal in graphical session. That doesn't work with ssh remote :/

**Comment by paladini** [comment]
That's it, the comment by @vanson44 is right.
