### ISSUE TITLE
ERROR File NOT Found: Player

### ISSUE THREAD

**Issue by dowodenum** [paladini/aax2mp3-easy#22]
Script was working great until a month or so ago. Now I get this error when running:

```Traceback (most recent call last):
  File "audible-activator-master/audible-activator.py", line 182, in <module>
    fetch_activation_bytes(username, password, options)
  File "audible-activator-master/audible-activator.py", line 82, in fetch_activation_bytes
    executable_path=chromedriver_path)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

2020-03-24 00:43:25-0700 ERROR File NOT Found: Player
```

If I copy chromedriver into /bin/ then I get: 

```
Traceback (most recent call last):
  File "audible-activator-master/audible-activator.py", line 182, in <module>
    fetch_activation_bytes(username, password, options)
  File "audible-activator-master/audible-activator.py", line 117, in fetch_activation_bytes
    + 'customer_token=' + data["playerToken"] + "&action=de-register"
KeyError: 'playerToken'
2020-03-24 00:44:20-0700 ERROR File NOT Found: Running
```

**Comment by dowodenum** [comment]
Okay, I solved it - user error. The script downloads the latest Chromedriver and I had an older version of Chrome installed. That took care of `File NOT Found: Player`, and I didn't have to move it into /bin/.

As for `KeyError: 'playerToken'`, Selenium was driving Chrome so fast I never noticed it was asking to text me an OTP code, crashing and going back to the Audible homepage. It probably only asked  due to my being on a VPN.

So I logged in through Chrome manually, then tried again from the same IP (with an active cookie) and it didn't ask for the OTP code, allowing the script to progress normally.

Thanks again for your hard work!
