### ISSUE TITLE
ImportError: No Module named requests from audible-activator-master/audible-activator.py

### ISSUE THREAD

**Issue by jackfusion** [paladini/aax2mp3-easy#25]
what running ./aax2mp3_easy.sh username password ABreathofSnowandAshesOutlanderBook6_ep6.aax

I get this error.

Traceback (most recent call last):
  File "audible-activator-master/audible-activator.py", line 10, in <module>
    import requests
ImportError: No module named requests

**Comment by paladini** [comment]
@jackfusion Hey there, are you running on Linux, right?

Try to install requests library from pip:

```
pip install requests
```

You can install for Python3 too:

```
pip3 install requests
```

(Not necessary if previous steps already worked) Other possible pip installation commands, that will work only according on how your environment is configured:

```
pip2.7 install requests
pip2 install requests
pip2.6 install requests
pip3 install requests
pip3.6 install requests
```

That should solve your problem!

**Comment by dougg0k** [comment]
Didnt work. 

```
> pip3 install requests

Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.22.0)
```

though both pip and pip3 goes to python3

**Comment by cedricdelpoux** [comment]
I have the same error :
```
Traceback (most recent call last):
  File "audible-activator-master/audible-activator.py", line 10, in <module>
    import requests
ImportError: No module named requests
```

I tried to install requests using `pip3 install requests`

But the error still appears
