### ISSUE TITLE
chromedriver unexpectedly exited

### ISSUE THREAD

**Issue by aussiDavid** [paladini/aax2mp3-easy#6]
I've put your code in to a docker container and run the following

```$ docker run -it aussidavid/aax2mp3-easy ./aax2mp3_easy.sh edward@gmail.com hpK1abc TheFilterBubble.aax```

and get the following output:

```
Davids-MacBook-Air-6:aax David$ docker run -it aussidavid/aax2mp3-easy ./aax2mp3_easy.sh edward@gmail.com hpK1abc TheFilterBubble.aax
Downloading AAXtoMP3...
--2018-02-05 02:07:32--  https://github.com/KrumpetPirate/AAXtoMP3/archive/master.zip
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/KrumpetPirate/AAXtoMP3/zip/master [following]
--2018-02-05 02:07:37--  https://codeload.github.com/KrumpetPirate/AAXtoMP3/zip/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4260 (4.2K) [application/zip]
Saving to: 'aaxtomp3.zip'

aaxtomp3.zip                        100%[==================================================================>]   4.16K  --.-KB/s    in 0.001s

2018-02-05 02:07:38 (3.61 MB/s) - 'aaxtomp3.zip' saved [4260/4260]

Archive:  aaxtomp3.zip
de01589b94dad479571fc79112182343a1f93af5
   creating: AAXtoMP3-master/
 extracting: AAXtoMP3-master/.gitignore
  inflating: AAXtoMP3-master/AAXtoMP3
  inflating: AAXtoMP3-master/LICENSE
  inflating: AAXtoMP3-master/README.md
Downloading audible-activator...
--2018-02-05 02:07:38--  https://github.com/paladini/audible-activator/archive/feature_login_as_arg.zip
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/paladini/audible-activator/zip/feature_login_as_arg [following]
--2018-02-05 02:07:39--  https://codeload.github.com/paladini/audible-activator/zip/feature_login_as_arg
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20892 (20K) [application/zip]
Saving to: 'audible-activator.zip'

audible-activator.zip               100%[==================================================================>]  20.40K  81.3KB/s    in 0.3s

2018-02-05 02:07:41 (81.3 KB/s) - 'audible-activator.zip' saved [20892/20892]

Archive:  audible-activator.zip
949bff7fe217e32dd8a50d4a1c371411efa96868
   creating: audible-activator-feature_login_as_arg/
  inflating: audible-activator-feature_login_as_arg/.gitignore
  inflating: audible-activator-feature_login_as_arg/AAS-parser.py
  inflating: audible-activator-feature_login_as_arg/AudibleGeneratePCPlayerID.c
  inflating: audible-activator-feature_login_as_arg/LICENSE
  inflating: audible-activator-feature_login_as_arg/README.md
  inflating: audible-activator-feature_login_as_arg/audible-activator.py
  inflating: audible-activator-feature_login_as_arg/common.py
  inflating: audible-activator-feature_login_as_arg/extract-activation-bytes.py
   creating: audible-activator-feature_login_as_arg/unused/
  inflating: audible-activator-feature_login_as_arg/unused/.gitconfig
Downloading Chrome-Driver-Latest...
--2018-02-05 02:07:41--  https://chromedriver.storage.googleapis.com/LATEST_RELEASE
Resolving chromedriver.storage.googleapis.com (chromedriver.storage.googleapis.com)... 216.58.199.48, 2404:6800:4006:803::2010
Connecting to chromedriver.storage.googleapis.com (chromedriver.storage.googleapis.com)|216.58.199.48|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5 [application/octet-stream]
Saving to: 'chromedriver-latest-release.txt'

chromedriver-latest-release.txt     100%[==================================================================>]       5  --.-KB/s    in 0s

2018-02-05 02:07:41 (163 KB/s) - 'chromedriver-latest-release.txt' saved [5/5]

--2018-02-05 02:07:41--  https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
Resolving chromedriver.storage.googleapis.com (chromedriver.storage.googleapis.com)... 216.58.199.48, 2404:6800:4006:803::2010
Connecting to chromedriver.storage.googleapis.com (chromedriver.storage.googleapis.com)|216.58.199.48|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3721349 (3.5M) [application/zip]
Saving to: 'chrome-driver-latest.zip'

chrome-driver-latest.zip            100%[==================================================================>]   3.55M  4.60MB/s    in 0.8s

2018-02-05 02:07:42 (4.60 MB/s) - 'chrome-driver-latest.zip' saved [3721349/3721349]

Archive:  chrome-driver-latest.zip
  inflating: chromedriver
Collecting requests
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |################################| 92kB 2.0MB/s
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2018.1.18-py2.py3-none-any.whl (151kB)
    100% |################################| 153kB 2.5MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |################################| 143kB 3.2MB/s
Collecting idna<2.7,>=2.5 (from requests)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |################################| 61kB 5.2MB/s
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |################################| 133kB 4.1MB/s
Installing collected packages: certifi, chardet, idna, urllib3, requests
Successfully installed certifi-2018.1.18 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22
Collecting selenium
  Downloading selenium-3.8.1-py2.py3-none-any.whl (942kB)
    100% |################################| 952kB 1.0MB/s
Installing collected packages: selenium
Successfully installed selenium-3.8.1
Traceback (most recent call last):
  File "audible-activator-feature_login_as_arg/audible-activator.py", line 148, in <module>
    fetch_activation_bytes(username, password, options)
  File "audible-activator-feature_login_as_arg/audible-activator.py", line 57, in fetch_activation_bytes
    executable_path=chromedriver_path)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service ./chromedriver unexpectedly exited. Status code was: 127

2018-02-05 02:07:46+0000 Decoding Player with auth code [*]...
Davids-MacBook-Air-6:aax David$
```

**Comment by paladini** [comment]
Can you check if the latest commit solved your issue? Just download the newest version from this repository and try it out. You help would be great for this project and for other users facing the same issue.
